export const CATEGORY_COLORS = {
  dining: "#f97316",
  groceries: "#22c55e",
  fruits: "#ef4444",
  snacks: "#d97706",
  liquor: "#9333ea",
  juices: "#eab308",
  beverages: "#14b8a6",
  movies: "#db2777",
  membership: "#6366f1",
  hobbies: "#f43f5e",
  sports: "#ea580c",
  rent: "#2563eb",
  electronics: "#0061ff",
  furniture: "#b45309",
  maintenance: "#ff4f00",
  supplies: "#06b6d4",
  pets: "#65a30d",
  services: "#8b5cf6",
  childcare: "#f9a8d4",
  clothing: "#d946ef",
  health: "#dc2626",
  personal: "#0ea5e9",
  education: "#1d4ed8",
  taxes: "#047857",
  insurance: "#0f766e",
  savings: "#0d9488",
  fuel: "#b91c1c",
  parking: "#4f46e5",
  cab: "#ca8a04",
  flight: "#0284c7",
  bicycle: "#16a34a",
  bus: "#c2410c",
  metro: "#98A1BC",
  train: "#346739",
  electricity: "#facc15",
  water: "#3b82f6",
  cleaning: "#0891b2",
  gas: "#fb7185",
  internet: "#4338ca",
  phone: "#15803d",
  uncategorized: "#c2185b",
};

export const CATEGORY_OPTIONS = [
  { value: "dining", label: "Dining Out", icon: "fas fa-utensils" },
  { value: "groceries", label: "Groceries", icon: "fas fa-shopping-basket" },
  { value: "fruits", label: "Fruits", icon: "fas fa-apple-alt" },
  { value: "snacks", label: "Snacks", icon: "fas fa-cookie-bite" },
  { value: "liquor", label: "Liquor & Spirits", icon: "fas fa-wine-glass-alt" },
  { value: "juices", label: "Juices", icon: "fas fa-glass-whiskey" },
  { value: "beverages", label: "Non-Alcoholic Beverages", icon: "fas fa-mug-hot" },
  { value: "movies", label: "Movies", icon: "fas fa-film" },
  { value: "membership", label: "Membership", icon: "fas fa-id-card" },
  { value: "hobbies", label: "Hobbies", icon: "fas fa-palette" },
  { value: "sports", label: "Sports & Recreation", icon: "fas fa-basketball-ball" },
  { value: "rent", label: "Rent & Mortgage", icon: "fas fa-home" },
  { value: "electronics", label: "Electronics", icon: "fas fa-tv" },
  { value: "furniture", label: "Furniture & Decor", icon: "fas fa-couch" },
  { value: "maintenance", label: "Maintenance & Repairs", icon: "fas fa-tools" },
  { value: "supplies", label: "Household Supplies", icon: "fas fa-box-open" },
  { value: "pets", label: "Pets", icon: "fas fa-paw" },
  { value: "services", label: "Services", icon: "fas fa-concierge-bell" },
  { value: "childcare", label: "Childcare", icon: "fas fa-baby" },
  { value: "clothing", label: "Clothing & Accessories", icon: "fas fa-tshirt" },
  { value: "health", label: "Healthcare", icon: "fas fa-heartbeat" },
  { value: "personal", label: "Personal Care", icon: "fas fa-shower" },
  { value: "education", label: "Education", icon: "fas fa-graduation-cap" },
  { value: "taxes", label: "Taxes", icon: "fas fa-receipt" },
  { value: "insurance", label: "Insurance", icon: "fas fa-shield-alt" },
  { value: "savings", label: "Savings", icon: "fas fa-piggy-bank" },
  { value: "fuel", label: "Fuel", icon: "fas fa-gas-pump" },
  { value: "parking", label: "Parking", icon: "fas fa-parking" },
  { value: "cab", label: "Cab", icon: "fas fa-taxi" },
  { value: "flight", label: "Flight", icon: "fas fa-plane" },
  { value: "bicycle", label: "Bicycle", icon: "fas fa-bicycle" },
  { value: "bus", label: "Bus", icon: "fas fa-bus" },
  { value: "metro", label: "Metro", icon: "fas fa-subway" },
  { value: "train", label: "Train", icon: "fas fa-train" },
  { value: "electricity", label: "Electricity", icon: "fas fa-bolt" },
  { value: "water", label: "Water", icon: "fas fa-tint" },
  { value: "cleaning", label: "Cleaning", icon: "fas fa-broom" },
  { value: "gas", label: "Gas", icon: "fas fa-burn" },
  { value: "internet", label: "Internet & Cable", icon: "fas fa-wifi" },
  { value: "phone", label: "Phone", icon: "fas fa-phone" },
  { value: "uncategorized", label: "Uncategorized", icon: "fas fa-question-circle" },
];

const CATEGORY_OPTION_MAP = Object.fromEntries(
  CATEGORY_OPTIONS.map((option) => [option.value, option]),
);

export const CATEGORY_GROUPS = [
  { label: "Food", values: ["dining", "groceries", "fruits", "snacks"] },
  { label: "Drinks", values: ["liquor", "juices", "beverages"] },
  { label: "Entertainment", values: ["movies", "membership", "hobbies", "sports"] },
  {
    label: "Home",
    values: ["rent", "electronics", "furniture", "maintenance", "supplies", "pets", "services"],
  },
  {
    label: "Life",
    values: ["childcare", "clothing", "health", "personal", "education", "taxes", "insurance", "savings"],
  },
  { label: "Transportation", values: ["fuel", "parking", "cab", "flight", "bicycle", "bus", "metro", "train"] },
  { label: "Utilities", values: ["electricity", "water", "cleaning", "gas", "internet", "phone"] },
  { label: "Other", values: ["uncategorized"] },
].map((group) => ({
  label: group.label,
  options: group.values
    .map((value) => CATEGORY_OPTION_MAP[value])
    .filter(Boolean),
}));

export function getCategoryDisplay(category) {
  return (
    CATEGORY_OPTIONS.find((option) => option.value === category) || {
      value: category,
      label: category ? category.charAt(0).toUpperCase() + category.slice(1) : "Uncategorized",
      icon: "fas fa-circle",
      color: CATEGORY_COLORS[category] || CATEGORY_COLORS.uncategorized,
    }
  );
}
