export const CATEGORY_COLORS = {
  dining: "#f97316",
  groceries: "#22c55e",
  fruits: "#ef4444",
  snacks: "#d97706",
  liquor: "#9333ea",
  juices: "#eab308",
  beverages: "#14b8a6",
  movies: "#db2777",
  membership: "#6366f1",
  hobbies: "#f43f5e",
  sports: "#ea580c",
  rent: "#2563eb",
  electronics: "#475569",
  furniture: "#b45309",
  maintenance: "#4b5563",
  supplies: "#06b6d4",
  pets: "#65a30d",
  services: "#8b5cf6",
  childcare: "#f9a8d4",
  clothing: "#d946ef",
  health: "#10b981",
  personal: "#0ea5e9",
  education: "#1d4ed8",
  taxes: "#047857",
  insurance: "#0f766e",
  fuel: "#b91c1c",
  parking: "#4f46e5",
  cab: "#ca8a04",
  flight: "#0284c7",
  bicycle: "#16a34a",
  bus: "#c2410c",
  metro: "#7e22ce",
  train: "#334155",
  electricity: "#eab308",
  water: "#3b82f6",
  cleaning: "#0891b2",
  gas: "#f97316",
  internet: "#4338ca",
  phone: "#15803d",
  uncategorized: "#6b7280",
};

export const CATEGORY_OPTIONS = [
  { value: "dining", label: "Dining Out" },
  { value: "groceries", label: "Groceries" },
  { value: "fruits", label: "Fruits" },
  { value: "snacks", label: "Snacks" },
  { value: "liquor", label: "Liquor & Spirits" },
  { value: "juices", label: "Juices" },
  { value: "beverages", label: "Non-Alcoholic Beverages" },
  { value: "movies", label: "Movies" },
  { value: "membership", label: "Membership" },
  { value: "hobbies", label: "Hobbies" },
  { value: "sports", label: "Sports & Recreation" },
  { value: "rent", label: "Rent & Mortgage" },
  { value: "electronics", label: "Electronics" },
  { value: "furniture", label: "Furniture & Decor" },
  { value: "maintenance", label: "Maintenance & Repairs" },
  { value: "supplies", label: "Household Supplies" },
  { value: "pets", label: "Pets" },
  { value: "services", label: "Services" },
  { value: "childcare", label: "Childcare" },
  { value: "clothing", label: "Clothing & Accessories" },
  { value: "health", label: "Healthcare" },
  { value: "personal", label: "Personal Care" },
  { value: "education", label: "Education" },
  { value: "taxes", label: "Taxes" },
  { value: "insurance", label: "Insurance" },
  { value: "fuel", label: "Fuel" },
  { value: "parking", label: "Parking" },
  { value: "cab", label: "Cab" },
  { value: "flight", label: "Flight" },
  { value: "bicycle", label: "Bicycle" },
  { value: "bus", label: "Bus" },
  { value: "metro", label: "Metro" },
  { value: "train", label: "Train" },
  { value: "electricity", label: "Electricity" },
  { value: "water", label: "Water" },
  { value: "cleaning", label: "Cleaning" },
  { value: "gas", label: "Gas" },
  { value: "internet", label: "Internet & Cable" },
  { value: "phone", label: "Phone" },
  { value: "uncategorized", label: "Uncategorized" },
];

export function getCategoryDisplay(category) {
  return (
    CATEGORY_OPTIONS.find((option) => option.value === category) || {
      value: category,
      label: category ? category.charAt(0).toUpperCase() + category.slice(1) : "Uncategorized",
    }
  );
}
